version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: defyne
      MYSQL_USER: cake
      MYSQL_PASSWORD: cake
    networks:
      - cakesite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - cakesite

  cakephp:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      MYSQL_DB_HOST: db:3306
      MYSQL_DB_USER: cake
      MYSQL_DB_PASSWORD: cake
    networks:
      - cakesite
networks:
  cakesite:
volumes:
  db_data: { driver: local }
