version: '3'

services:
  # Database
  db:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - cakesite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - cakesite

  cakephp:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      MYSQL_URL: db
      MYSQL_DB_HOST: db:3306
      MYSQL_DB_USER: cake
      MYSQL_DB_PASSWORD: cake
    networks:
      - cakesite
networks:
  cakesite:
volumes:
  db_data: { driver: local }
